In [39]:
import numpy as np

In [21]:
arreglo_1 = np.array([1,2,3,4,5,6])
type(arreglo_1)

numpy.ndarray

In [22]:
arreglo_1

array([1, 2, 3, 4, 5, 6])

In [23]:
arreglo_1[:]

array([1, 2, 3, 4, 5, 6])

In [24]:
arreglo_1[0]

1

In [25]:
arreglo_1[0:5]

array([1, 2, 3, 4, 5])

In [26]:
arreglo_1[-1]

6

In [44]:
arreglo_2 = np.array([[1,2,3,4],[5,6,7,8] ])

In [45]:
arreglo_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
arreglo_2[0,1]

2

In [47]:
arreglo_2[:,1]

array([2, 6])

In [51]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]

In [61]:
array = np.array([[1 , 6, 11], [2, 7, 12], [3, 8, 13], [4, 9, 14], [5, 10, 15]])

In [62]:
array

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [64]:
array.shape

(5, 3)

In [69]:
array[:, 1]

array([ 6,  7,  8,  9, 10])

In [82]:
array_2 = np.array(range(5,56))

In [83]:
array_2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [84]:
array_2[4] = 23

In [85]:
array_2

array([ 5,  6,  7,  8, 23, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

In [89]:
array_2.size

51

In [99]:
array_3 = np.zeros([51])
for n in range(1,array_2.size+1):
    array_3[51-n] = array_2[n-1]

In [101]:
array_3

array([55., 54., 53., 52., 51., 50., 49., 48., 47., 46., 45., 44., 43.,
       42., 41., 40., 39., 38., 37., 36., 35., 34., 33., 32., 31., 30.,
       29., 28., 27., 26., 25., 24., 23., 22., 21., 20., 19., 18., 17.,
       16., 15., 14., 13., 12., 11., 10., 23.,  8.,  7.,  6.,  5.])

In [146]:
array_2[::-1]

array([55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39,
       38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 23,  8,  7,  6,  5])

In [105]:
array_e = np.array([1,2,3,4])
array_d = np.diag(array_e)
array_e
array_d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [150]:
array_2[1::2]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50, 52, 54])

In [126]:
array_2[array_2%2==0][:5]

array([ 6,  8, 10, 12, 14])

In [113]:
array_4 = np.zeros(array_2.size)
array_4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
array_4 = np.diag(array_2[array_2%2==0][:5])
array_4

array([[ 6,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0, 10,  0,  0],
       [ 0,  0,  0, 12,  0],
       [ 0,  0,  0,  0, 14]])

In [132]:
array_4.ndim

2

In [138]:
array_5 = np.random.random((3, 5))
array_5

array([[0.03563634, 0.91377753, 0.33570465, 0.00665764, 0.82600695],
       [0.99796666, 0.15402895, 0.23997654, 0.02183959, 0.06261302],
       [0.13500716, 0.46300831, 0.39605102, 0.37551004, 0.79507498]])

In [141]:
array_5 @ array_4

array([[ 0.21381802,  7.31022023,  3.35704653,  0.07989163, 11.56409735],
       [ 5.98779999,  1.23223157,  2.39976537,  0.26207511,  0.87658231],
       [ 0.81004293,  3.70406649,  3.96051016,  4.50612052, 11.13104971]])